--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Herói', 'Camisa Batman', '29.99', 1);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Herói', 'Camisa Batman', '29.99', 2);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Herói', 'Camisa Batman', '29.99', 3);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Herói', 'Camisa Batman', '29.99', 4);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Filme', 'Camisa Minions', '29.99', 1);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Jogo', 'Camisa Super Mario Bros.', '29.99', 3);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Série', 'Camisa Game of Thrones', '29.99', 2);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Série', 'Camisa Seinfeld', '19.99', 1);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Série', 'Camisa Breaking Bad', '29.99', 4);
--INSERT INTO `ecommerce`.`products` (`category`, `name`, `price`, `product_size`) VALUES ('Jogo', 'Camisa Mortal Kombat', '29.99', 3);
--
